# Generated by Django 5.2.8 on 2025-12-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_hod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
