# Generated by Django 4.2.7 on 2026-08-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_practicalcenter_program_indexinformation_and_more'),
        ('users', '0005_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.program'),
        ),
    ]
