# Generated by Django 5.2.8 on 2025-11-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_grade_grade_points_semester_is_registration_active_and_more'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='semester',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], default='first', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_authorization_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='level',
            field=models.CharField(choices=[('100', 'Level 1'), ('200', 'Level 2'), ('300', 'Level 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash'), ('pos', 'POS')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('level', 'department', 'session', 'semester')},
        ),
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_data', models.JSONField(default=dict)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_details', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Paystack Transaction',
                'verbose_name_plural': 'Paystack Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
