# Generated by Django 5.2.8 on 2026-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feestructure_semester_payment_paystack_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='allow_part_payment',
            field=models.BooleanField(default=False, help_text='Is this invoice eligible for part-payment?'),
        ),
    ]
