# Generated by Django 5.2.8 on 2026-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_allow_part_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='min_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum partial payment amount if part payment is allowed', max_digits=10, null=True),
        ),
    ]
