# Generated by Django 4.2.7 on 2026-08-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_practicalcenter_program_indexinformation_and_more'),
        ('finance', '0004_invoice_min_installment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=True, help_text='Optional fees (accommodation, uniform, etc.) vs. mandatory ones.')),
                ('requires_selection', models.BooleanField(default=False, help_text='If true, paying this fee redirects the student to an additional step (e.g. Practical Fee -> center selection).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fee Item',
                'verbose_name_plural': 'Fee Items',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='course_registration',
            field=models.ForeignKey(blank=True, help_text='Set when this invoice is a carry-over exam fee tied to a specific re-registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='academics.courseregistration'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_item',
            field=models.ForeignKey(blank=True, help_text='Set when this invoice is for an ad-hoc fee item (accommodation, index, practical, etc.) rather than tuition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.feeitem'),
        ),
        migrations.CreateModel(
            name='FeeItemCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('semester', models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10, null=True)),
                ('level', models.CharField(blank=True, choices=[('100', 'Level 1'), ('200', 'Level 2'), ('300', 'Level 3')], max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False, help_text='Nothing is chargeable until the Bursar activates a real price.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='finance.feeitem')),
            ],
            options={
                'verbose_name': 'Fee Item Charge',
                'verbose_name_plural': 'Fee Item Charges',
                'ordering': ['fee_item__name', '-session'],
                'unique_together': {('fee_item', 'session', 'semester', 'level')},
            },
        ),
    ]
