# Generated by Django 5.2.8 on 2025-11-24 18:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('max_applications', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Session',
                'verbose_name_plural': 'Admission Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('session', models.CharField(max_length=9)),
                ('programme_type', models.CharField(choices=[('nce', 'NCE'), ('degree', 'Degree'), ('diploma', 'Diploma'), ('pgd', 'PGD'), ('masters', 'Masters')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nationality', models.CharField(default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='LGA')),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('olevel_results', models.JSONField(default=dict)),
                ('jamb_score', models.IntegerField(blank=True, null=True)),
                ('previous_institution', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='applications/photos/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('olevel_certificate', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_choice_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_choice_applications', to='academics.department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('second_choice_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_choice_applications', to='academics.department')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('matric_number', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(default='100', max_length=10)),
                ('session', models.CharField(max_length=9)),
                ('letter_content', models.TextField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_letter', to='admissions.application')),
            ],
            options={
                'verbose_name': 'Admission Letter',
                'verbose_name_plural': 'Admission Letters',
                'ordering': ['-issued_date'],
            },
        ),
    ]
