# Generated by Django 5.2.8 on 2025-12-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_grade_grade_points_semester_is_registration_active_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approved_by_exam_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_officer_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='approved_by_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_approvals', to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='registration',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved_lecturer', 'Approved by Lecturer'), ('approved_exam_officer', 'Approved by Exam Officer'), ('registered', 'Registered'), ('rejected_lecturer', 'Rejected by Lecturer'), ('rejected_exam_officer', 'Rejected by Exam Officer'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
