# Generated by Django 5.2.8 on 2025-12-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_registration_approved_by_exam_officer_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('o_level', "O'Level Result"), ('jamb_result', 'JAMB Result'), ('jamb_admission', 'JAMB Admission Letter'), ('local_government', 'Local Government Certificate'), ('medical_report', 'Medical Report'), ('passport_photo', 'Passport Photograph'), ('acceptance_fee', 'Acceptance Fee Receipt'), ('school_fees', 'School Fees Receipt'), ('other', 'Other Document')], max_length=50)),
                ('document_name', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='student_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_update', 'Requires Update')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('registration', 'Registration Issue'), ('payment', 'Payment Issue'), ('document', 'Document Upload Issue'), ('course', 'Course Registration'), ('result', 'Result Issue'), ('personal_info', 'Personal Information'), ('other', 'Other Issue')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queries', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_queries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Query',
                'verbose_name_plural': 'Student Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('registration_data', models.JSONField(default=dict)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_emergency_regs', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_registrations', to='users.student')),
            ],
            options={
                'verbose_name': 'Emergency Registration',
                'verbose_name_plural': 'Emergency Registrations',
                'ordering': ['-approved_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
