# Generated by Django 5.2.8 on 2025-12-09 05:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentdocument_studentquery_emergencyregistration'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='CourseRegistration',
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['registration_date'], 'verbose_name': 'Course Registration', 'verbose_name_plural': 'Course Registrations'},
        ),
    ]
