# Generated by Django 5.2.8 on 2025-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_rename_registration_courseregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
