# Generated by Django 5.2.8 on 2025-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseregistration_grade_courseregistration_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
