# Generated by Django 5.2.8 on 2025-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_grade_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='ca_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
