# Generated by Django 5.2.8 on 2025-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_grade_ca_score_grade_exam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_published',
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft (Lecturer Only)'), ('submitted', 'Submitted (Waiting for HOD)'), ('hod_approved', 'Approved (Waiting for Exam Officer)'), ('verified', 'Verified (Waiting for Registrar)'), ('published', 'Published (Visible to Student)')], default='draft', max_length=20),
        ),
    ]
