# Generated by Django 5.2.8 on 2026-01-26 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_grade_is_published_grade_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='score',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.enrollment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(choices=[('A', 'A (4.0)'), ('B', 'B (3.0)'), ('C', 'C (2.0)'), ('D', 'D (1.0)'), ('E', 'E'), ('F', 'F (0.0)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='session',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicLevelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300')], max_length=10, unique=True)),
                ('is_registration_open', models.BooleanField(default=True)),
                ('current_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_configs', to='academics.semester')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
