# Generated by Django 4.2.27 on 2026-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_announcement_audience_notification_assignedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g. 2026/2027', max_length=9)),
                ('level', models.CharField(blank=True, choices=[('100', 'Level 1'), ('200', 'Level 2'), ('300', 'Level 3')], help_text='Blank = applies to all levels', max_length=10)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text="Display sequence (matches the official calendar's S/N)")),
                ('activity', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text="As stated on the official calendar, e.g. '4 weeks', '10 days'", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Calendar Event',
                'verbose_name_plural': 'Academic Calendar Events',
                'ordering': ['session', 'level', 'semester', 'order'],
            },
        ),
    ]
