# Generated by Django 4.2.27 on 2026-09-28 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0016_seed_academic_calendar_2026_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=list, help_text='List of {student_id, prev_level, prev_status} for every student this run touched.')),
                ('graduated_count', models.PositiveIntegerField(default=0)),
                ('promoted_to_300_count', models.PositiveIntegerField(default=0)),
                ('promoted_to_200_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs', to=settings.AUTH_USER_MODEL)),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs_undone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Run',
                'verbose_name_plural': 'Promotion Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
